console.log("=".repeat(30))
console.log("McDONALD'S RECEIPT".padStart(25))
console.log("-".repeat(30))
console.log("Order Details".padStart(22))
console.log("-".repeat(30))
console.log("Item".padEnd(11) + "Quantity".padEnd(11) + "Price")
console.log("-".repeat(30))
console.log("🍔 Burger".padEnd(15) + "1".padEnd(8) + "2.99")
console.log("🍟 Fries".padEnd(15) + "1".padEnd(8) + "2.49")
console.log("🥤 Soda".padEnd(15) + "1".padEnd(8) + "1.99")
console.log("-".repeat(30))
console.log("Total".padEnd(23) + "7.47")
console.log("=".repeat(30))